config/routes.rb
Rails.application.routes.draw do
  root "logsheets#index"
  devise_for :users

  resources :logsheets
end

app/models/adventure.rb
class Adventure < ApplicationRecord
  belongs_to :logsheet
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/charclass.rb
class Charclass < ApplicationRecord
  belongs_to :logsheet
end

app/models/logsheet.rb
class Logsheet < ApplicationRecord
  belongs_to :user
  has_many :adventures, dependent: :destroy
  has_many :charclasses, dependent: :destroy
  has_many :magicitems, dependent: :destroy
  has_one :tieronetcp, dependent: :destroy
  has_one :tiertwotcp, dependent: :destroy
  has_one :tierthreetcp, dependent: :destroy
  has_one :tierfourtcp, dependent: :destroy

end

app/models/magicitem.rb
class Magicitem < ApplicationRecord
  belongs_to :logsheet
end

app/models/tierfourtcp.rb
class Tierfourtcp < ApplicationRecord
  belongs_to :logsheet
end

app/models/tieronetcp.rb
class Tieronetcp < ApplicationRecord
  belongs_to :logsheet
end

app/models/tierthreetcp.rb
class Tierthreetcp < ApplicationRecord
  belongs_to :logsheet
end

app/models/tiertwotcp.rb
class Tiertwotcp < ApplicationRecord
  belongs_to :logsheet
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :logsheets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    end

end

app/controllers/logsheets_controller.rb
class LogsheetsController < ApplicationController
  before_action :set_logsheet, only: [:show, :edit, :update, :destroy]

  def index
    @logsheets = current_user.logsheets
  end

  def show
  end

  def new
    @logsheet = Logsheet.new
    @charclass = Charclass.new
  end

  def create
    @logsheet = current_user.logsheets.new(logsheet_params)
    @charclass = @logsheet.charclasses.new(charclass_params)
    if @charclass.save
      flash[:success] = "Class Added"
    end

    if @logsheet.save
      flash[:success] = "Logsheet Created"
      redirect_to logsheets_path
    else
      flash[:error] = "Error #{@logsheet.errors.full_messages.join("\n")}"
      render :new
    end
  end

  def edit
  end

  def update
    if @logsheet.update(logsheet_params)
      redirect_to logsheets_path
    else
      render :edit
    end
  end

  def destroy
    @logsheet.destroy
    redirect_to logsheets_path
  end

  private
    def logsheet_params
      params.require(:logsheet).permit(:char, :gold, :downtime, :renown, :race, :dci, :exp)
    end

    def charclass_params
      params.require(:logsheet).permit(:name, :lvls)
    end

    # don't just find by the logsheet model or you may potentially be able to view other users logsheets
    def set_logsheet
      @logsheet = current_user.logsheets.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logsheets_helper.rb
module LogsheetsHelper
end

app/views/layouts/_navbar.html.erb
<div class="ui huge menu inverted">
  <%= link_to "Home", logsheets_path, class:"item"%>
  <div class="right menu">
  <%= link_to "Log Out", destroy_user_session_path, method: :delete, class:"active item red" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AL-Logsheet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar'%>
    <div class="ui container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <%= yield %>
    </div>
  </body>
</html>

app/views/logsheets/edit.html.erb
<h1>Logsheets#edit</h1>
<p>Find me in app/views/logsheets/edit.html.erb</p>

app/views/logsheets/index.html.erb
<h2>Welcome <%= current_user.first_name %></h2>
<hr />
<%= link_to "New Logsheet", new_logsheet_path, class:"ui button green inverted" %>
<h3>Your Logsheets</h3>
<div class="ui divided items">
  <% @logsheets.each do |logsheet| %>
  <div class="item">
    <div class="image">
      <img src="">
    </div>
    <div class="content">
      <%= link_to logsheet.char, logsheet, class: "header" %>
      <div class="meta">
        <span>DCI#<%= logsheet.dci %></span>
      </div>
      <div class="description">
      <p><i class="child icon"></i><%= logsheet.race %></p>
      <% logsheet.charclasses.each do |charclass|%>
        <p><i class="shield alternate icon"></i><%= charclass.name %> - <%= charclass.lvls %></p>
        <% end %>
      </div>
      <div class="extra">
        <%= logsheet.gold %> GP - <%= logsheet.exp %> Exp - <%= logsheet.downtime %> <i class="bed icon"></i>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/logsheets/new.html.erb
<h1>New Logsheet</h1>
<%= form_with(model: @logsheet, local: true, class: "ui form") do |f| %>

  <div class="two fields">

    <div class="four wide field">
      <%= f.label "Character Name" %>
      <%= f.text_field :char, required: true, placeholder: "Character Name", class:"ui input"%>
    </div>

    <div class="four wide field">
      <%= f.label :dci %>
      <%= f.text_field :dci, placeholder: "DCI #" %>
    </div>
    
  </div>
  <div class="three fields">

    <div class="three wide field">
      <%= f.label :race %>
      <%= f.text_field :race, required: true, placeholder: "Race" %>
    </div>

    <div class="three wide field">
      <%= f.label "Class" %>
      <%= f.text_field :name, required: true, placeholder: "Class" %>
    </div>
    <div class="one wide field">
      <%= f.label "Level" %>
      <%= f.text_field :lvls, min: 1, required: true, value: 1, readonly: true %>
    </div>

  </div>
  <div class="four fields">

    <div class="two wide field">
      <div class="ui labeled input">
        <%= f.label "XP", class:"ui label" %>
        <%= f.number_field :exp, min: 0, required: true, value: 0, readonly: true%>
      </div>
    </div>
    <div class="two wide field">
      <div class="ui labeled input">
        <%= f.label "G", class:"ui label" %>
        <%= f.number_field :gold, min: 0, required: true, placeholder: 0 %>
      </div>
    </div>
    <div class="two wide field">
      <div class="ui labeled input">
        <%= f.label "DT", class:"ui label" %>
        <%= f.number_field :downtime, min: 0, required: true, value: 0, readonly: true %>
      </div>
    </div>

    <div class="two wide field">
      <div class="ui labeled input">
        <%= f.label "RN", class:"ui label" %>
        <%= f.number_field :renown, min: 0, required: true, value: 0, readonly: true %>
      </div>
    </div>

  </div>

  <%= f.submit class: "ui button green inverted"%>
<% end %>

app/views/logsheets/show.html.erb
<div class="ui raised segments">
  <div class="ui red center aligned segment">
      <h1><%= @logsheet.char %></h1>
      <p>DCI #<%= @logsheet.dci %></p>
  </div>
  <div class="ui equal width center aligned padded grid">
      <div class="row">
            <div class="column">
                  <div class="ui segment">
                        <p><%= @logsheet.race %></p>
                  </div>
            </div>
            <div class="column">
                  <div class="ui segment">
                        <% @logsheet.charclasses.each do |charclass| %>
                             <%= charclass.name %> - <%= charclass.lvls %>
                        <% end %>  
                  </div> 
            </div>
            <div class="column">
                  <div class="ui segment">
                        <%= @logsheet.exp %> EXP
                  </div>
            </div>
      </div>
      <div class="row">
            <div class="column">
                  <div class="ui segment">
                       <%= @logsheet.gold %> Gold
                  </div>
            </div>
            <div class="column">
                  <div class="ui segment">
                        <%= @logsheet.downtime %> Downtime
                  </div>
            </div>
            <div class="column">
                  <div class="ui segment">
                        <%= @logsheet.renown %> Renown
                  </div>
            </div>
      </div>
  </div>
</div>

<ul>
      <% @logsheet.magicitems.each do |magic| %>
        <li><%= magic.name %> - <%= magic.consumable %> - <%= magic.tcpvalue %></li>
      <% end %>

</ul>

<%= @logsheet.tieronetcp %>
<%= @logsheet.tiertwotcp %>
<%= @logsheet.tierthreetcp %>
<%= @logsheet.tierfourtcp %>


<ul>
      <% @logsheet.adventures.each do |adventure| %>
        <li><%= adventure.name %> - <%= adventure.notes %></li>
      <% end %>
</ul>


      <%= link_to 'Delete', @logsheet, method: :delete %>